title: Stuart Holland â€“ Agentic AI Engineer
description: AI Engineering Portfolio powered by LangGraph, Claude, RAG, and LangChain
remote_theme: daattali/beautiful-jekyll@master

plugins:
  - jekyll-remote-theme
